Add VC2 Plans as aliases
vultr/terraform-datalib-vultr pull request #10
Opened 2020-06-24 04:54 UTC by edward-murrell

This adds the ability select plans by a shortname, rather than a integer ID.

## Description
The VC2 plan is identified by VCPU, RAM, and Storage.

For example:
```hcl
resource "vultr_server" "server0" {
  plan_id = module.vultr_lib.vc1_m1_s1x25
}

### Checklist:

* :heavy_check_mark: Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* :heavy_check_mark: Have you linted your code locally prior to submission?
* :heavy_check_mark: Have you successfully ran tests with your changes locally?

2020-06-24 13:53 UTC, ddymko commented
@edward-murrell 

Thanks for taking the time to do this! 

We do have one request could we change the naming scheme? Right now it looks like we are blending multiple instance types VC2, VHF (High Frequency), and VDC (Dedicated)

I am thinking it might be better to break them out into their own sets


https://api.vultr.com/v1/plans/list?type=vc2
```
Vultr Cloud Compute (VC2)

- vc2-512mb-1vcpu-ipv6
- vc2-512mb-1vcpu

- vc2-1vcpu-1gb
- vc2-1vcpu-2gb
- vc2-2vcpu-4gb
- vc2-4vcpu-8gb
- vc2-6vcpu-16gb
- vc2-8vcpu-64gb
- vc2-16vcpu-64gb
- vc2-24vcpu-97gb
```

https://api.vultr.com/v1/plans/list?type=vhf
```
Vultr High Frequency (VHF)

- vhf-1vcpu-1gb
- vhf-1vcpu-2gb
- vhf-2vcpu-4gb
- vhf-3vcpu-8gb
- vhf-4vcpu-16gb
- vhf-8vcpu-32gb
- vhf-12vcpu-48gb
```

https://api.vultr.com/v1/plans/list?type=vdc2
```
Vultr Dedicated Cloud (VDC)

- vdc-4vcpu-8gb
- vdc-4vcpu-16gb
- vdc-6vcpu-24gb
- vdc-8vcpu-32gb
```

There is also baremetal which has a different API call
https://api.vultr.com/v1/plans/list_baremetal
```
Vultr Bare Metal (VBM)

- vbm-4cpu-32gb
```

2020-06-24 15:43 UTC, ddymko requested changes
https://github.com/vultr/terraform-datalib-vultr/pull/10#issuecomment-648834797

2020-06-24 22:50 UTC, edward-murrell commented
@ddymko Yep, that's not a big deal. I'll probably write a python script to build this automatically, and that could become part of a CI process to build these files automatically in the future.

2020-06-25 00:34 UTC, edward-murrell commented
@ddymko I've added those VM plans. The bare metal plan may come later.

Since the plan aliases are now generated from the attached python script, and the `plan_id` is referenced directly, the http lookup at the top of the file doesn't do anything anymore, so I've removed that from `plans.tf`. A similar system could be used to generate various other aliases in this module.

2020-06-25 12:52 UTC, ddymko commented
@Oogy mind taking a look?

2020-06-25 13:02 UTC, ddymko commented
@edward-murrell`512mb / ipv6 instances` Yup these are only available via the UI.

This looks good!

Also, fwiw we are working on a V2 of the API that's where the naming convention for plans came from (regions also have a renaming).

2020-06-25 13:41 UTC, Oogy commented
@edward-murrell 
Could we have the output names changed to use underscores instead of hyphens to keep with Terraform best practices? Other than that looks great and thank you for the script.

2020-06-25 23:12 UTC, edward-murrell commented
@ddymko That'd be excellent, I look forward to using v2 then.

@Oogy You're welcome.

No problem at all. Done. I've changed the hyphens to underscores in the script and the plans files.

2020-06-26 12:20 UTC, merged